(global-set-key (kbd "M-h") 'evil-backward-char)
(global-set-key (kbd "M-j") 'evil-next-line)
(global-set-key (kbd "M-k") 'evil-previous-line)
(global-set-key (kbd "M-l") 'evil-forward-char)
(my-undef-evil-key (kbd "M-."))
(my-undef-evil-key (kbd "C-a"))
(my-undef-evil-key (kbd "C-e"))
(global-set-key (kbd "M-a") 'beginning-of-visual-line)
(global-set-key (kbd "M-e") 'end-of-visual-line)
(global-set-key (kbd "M-f") 'scroll-up-command)
(global-set-key (kbd "M-*") 'pop-tag-mark)
(global-set-key (kbd "M-o") 'other-window)
(global-set-key (kbd "C-l") 'compile)

(my-set-evil-states-key '(normal motion visual) (kbd "/") 'isearch-forward)
(my-set-evil-states-key '(normal motion visual) (kbd "?") 'isearch-backward)
(my-set-evil-states-key '(normal motion visual) (kbd "n") 'isearch-repeat-forward)
(my-set-evil-states-key '(normal motion visual) (kbd "N") 'isearch-repeat-backward)
